include ${TOP}/conf/Makefile.${ARCH}
include ${TOP}/depend.mk.${ARCH}

O = ${TOP}/obj/${ARCH}
L = ${TOP}/lib/${ARCH}
B = ${TOP}/bin/${ARCH}

SUBMAKES= 

BUILD_EXES = 
FTN_BUILD_EXES = 
BUILD_LIBS = 

CSOURCE=

CXXSOURCE= 

HFILES= 

MISCFILES= *.tcl  *.py Makefile.dir Makefile

DOCFILES= 

DATAFILES= 

DEPENDSOURCE= $(CSOURCE) $(CXXSOURCE)

include ${TOP}/config.mk.${ARCH}


include ${TOP}/rules.mk
