CXX= g++
RM = rm
AR = ar rus
RANLIB = ranlib
MAKEDEPEND = makedepend
XLIBS = -L/usr/X11R6/lib -lXm -lXt -lXmu -lX11
GLLIBS = -lGLU -lGL -lGLw
CFLAGS += -DINTEL_LINUX -I/usr/X11R6/include -O2 -fPIC
SHR_EXT = so
SHR_LD = c++ -shared


